<?php $this->partial('base', ['title' => 'Connexion | Annonce Post']); ?>

<main>

	<div class="container mt-3 py-5">
		<h1 class="text-center pb-3">Se connecter</h1>

		<div class="col-6 mx-auto px-0 mt-3">
			<form>
				<div class="form-group">
					<label for="exampleInputEmail1">Adresse email</label>
					<input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Adresse email">
				</div>
				<div class="form-group">
					<label for="exampleInputPassword1">Mot de passe</label>
					<input type="password" class="form-control" id="exampleInputPassword1" placeholder="Mot de passe">
				</div>
				<button type="submit" class="btn btn-raised btn-primary mt-3">Connexion</button>
			</form>
		</div>
	</div>

</main>