version: '3.8'
services:
    app:
        container_name: app
        build: docker
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - '8080:80'
        expose:
            - '8080'
        depends_on:
            - mysql
        links:
            - mysql

    mysql:
        container_name: mysql
        image: mysql:8
        environment:
            HOST: mysql
            MYSQL_DATABASE: phalcon_app
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER_PASSWORD: root
        ports:
            - '3306:3306'