<div class="page-header">
    <h1>Congratulations!</h1>
</div>

<p>You're now flying with Phalcon. Great things are about to happen!</p>

<p>This page is located at <code>views/index/index.phtml</code></p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta id nihil quis quod ut! Beatae,  rem, voluptate.</p>

<p>Bonjour <?php echo $name;?></p>


<?php echo '<h1>Hello World !</h1>'; ?>


<ul>
	<?php for($i=1; $i<=count($tab); $i++): ?>
        <li><?php echo $tab[$i]; ?></li>
	<?php endfor; ?>
</ul>
