<div class="page-header">
    <h1>Congratulations!</h1>
</div>

<p>You're now flying with Phalcon. Great things are about to happen!</p>

<p>This page is located at <code>views/index/index.phtml</code></p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta id nihil quis quod ut! Beatae, consectetur debitis dolorum et exercitationem illum incidunt itaque mollitia nihil quas qui, quis rem, voluptate.</p>

<p>Bonjour <?php echo $name . " et " . $test;?></p>