<h1>Show Action</h1>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet et expedita facilis, fugiat harum inventore, ipsa ipsum itaque iure libero, maxime minus neque nihil odit pariatur quo quod sunt temporibus.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet et expedita facilis, fugiat harum inventore, ipsa ipsum itaque iure libero, maxime minus neque nihil odit pariatur quo quod sunt temporibus.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet et expedita facilis, fugiat harum inventore, ipsa ipsum itaque iure libero, maxime minus neque nihil odit pariatur quo quod sunt temporibus.</p>

<p>Bonjour <?php echo $var; ?></p>