<?php $this->partial('base', ['title' => 'Annonce Post | Index Show']); ?>

<main>

    <div class="container mt-5 pt-5">

        <h1>Bienvenue sur la page Show</h1>

        <h1>Show - IndexController</h1>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem consequuntur deserunt doloremque ducimus eaque illum in labore
            maiores, neque nostrum, optio provident quisquam reiciendis reprehenderit repudiandae sit suscipit unde veniam.
        </p>

        <h2><?php echo $data . " " . $var; ?></h2>

    </div>

</main>

