<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header mb-5">
    <h1 class="display-4">Modifier utilisateur</h1>
</div>

<hr class="hr">

<?php echo $this->getContent(); ?>

<form action="/save_modifier_utilisateur" class="form-horizontal" method="post">

	<div class="form-group">
		<label for="fieldLastname" class="control-label">Nom</label>
		<?php echo $this->tag->textField(["lastname", "size" => 30, "class" => "form-control", "id" => "fieldLastname"]) ?>
	</div>

	<div class="form-group">
		<label for="fieldFirstname" class="control-label">Prénom</label>
		<?php echo $this->tag->textField(["firstname", "size" => 30, "class" => "form-control", "id" => "fieldFirstname"]) ?>
	</div>

	<div class="form-group">
		<label for="fieldEmail" class="control-label">Adresse email</label>
		<?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
	</div>

	<div class="form-group">
		<label for="fieldPassword" class="control-label">Mot de passe</label>
		<?php echo $this->tag->passwordField(["password", "size" => 30, "class" => "form-control", "id" => "fieldPassword"]) ?>
	</div>

	<?php echo $this->tag->hiddenField("id") ?>

	<div class="form-group">
		<?php echo $this->tag->submitButton(['Enregistrer', "class" => "btn btn-secondary"]) ?>
	</div>
</form>

