<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["user", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Edit user</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="user/save" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldUsername" class="col-sm-2 control-label">Username</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["username", "size" => 30, "class" => "form-control", "id" => "fieldUsername"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPassword" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["password", "size" => 30, "class" => "form-control", "id" => "fieldPassword"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreatedat" class="col-sm-2 control-label">CreatedAt</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["createdAt", "size" => 30, "class" => "form-control", "id" => "fieldCreatedat"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUpdatedat" class="col-sm-2 control-label">UpdatedAt</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["updatedAt", "size" => 30, "class" => "form-control", "id" => "fieldUpdatedat"]) ?>
    </div>
</div>


    <?php echo $this->tag->hiddenField("id") ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
