<h1 class="h1">Liste des utilisateurs</h1>

<?php foreach ($users as $user): ?>
    <ul>
        <li> ID : <?php echo $user->getId(); ?></li>
        <li>Lastname : <?php echo $user->getLastname(); ?></li>
        <li>Firstname : <?php echo $user->getFirstname(); ?></li>
        <li>Email : <?php echo $user->getEmail(); ?></li>
        <li>Password : <?php echo $user->getPassword(); ?></li>
    </ul>
<?php endforeach; ?>