<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header mb-5">
	<h1 class="display-4">Connexion</h1>
</div>

<hr class="hr">

<?php echo $this->getContent(); ?>

<form action="/login" class="form-horizontal" method="post">
	<div class="form-group">
		<label for="fieldEmail" class="control-label">Adresse email</label>
		<?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail", "placeholder" => "Adresse email"]) ?>
	</div>

	<div class="form-group">
		<label for="fieldPassword" class="control-label">Mot de passe</label>
		<?php echo $this->tag->passwordField(["password", "size" => 30, "class" => "form-control", "id" => "fieldPassword", "placeholder" => "Mot de passe"]) ?>
	</div>

	<div class="form-group">
		<?php echo $this->tag->submitButton(["Connexion", "class" => "btn btn-secondary"]) ?>
	</div>
</form>