<?php $this->partial('base', ['title' => 'Annonce Post']); ?>

<main>

    <div class="banner-homepage py-1">
        <h1 class="display-1 font-weight-bold text-center text-white">Annonce Post</h1>
    </div>

    <div class="container mt-5 py-5">
        <h1 class="text-center pb-3">Les annonces : </h1>

        <div class="col-12 px-0 mt-3">
            <div class="row">

				<?php for($i=0; $i<9; $i++) : ?>
                    <div class="card mx-auto mb-5" style="width: 22rem;">
                        <img class="card-img-top" src="/img/item.jpg" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Item <?php echo $i+1; ?></h5>
                            <h6 class="card-subtitle mb-2 text-muted">50 €</h6>
                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        </div>
                        <div class="card-body">
                            <a href="/show/<?php echo $i; ?>" class="card-link">Voir l'annonce</a>
                        </div>
                    </div>
				<?php endfor;?>
            </div>
        </div>
    </div>

</main>