<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header mb-5">
	<h1 class="display-4">Modifier un post</h1>
</div>

<hr class="hr">

<?php echo $this->getContent(); ?>

<form action="/save_modifier_un_post" class="form-horizontal" method="post">

	<div class="form-group">
		<label for="fieldTitle" class="control-label">Titre du post</label>
		<?php echo $this->tag->textField(["title", "size" => 30, "class" => "form-control", "id" => "fieldTitle"]) ?>
	</div>

	<div class="form-group">
		<label for="fieldContent" class="control-label">Contenu du post</label>
		<?php echo $this->tag->textField(["content", "size" => 30, "class" => "form-control", "id" => "fieldContent"]) ?>
	</div>

	<?php echo $this->tag->hiddenField("id") ?>

	<div class="form-group">
		<?php echo $this->tag->submitButton(['Enregistrer', "class" => "btn btn-secondary"]) ?>
	</div>
</form>

